spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DEV.DATABASE.HOST}:${DEV.DATABASE.PORT}/${DEV.DATABASE.NAME}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${DEV.DATABASE.USERNAME}
    password: ${DEV.DATABASE.PASSWORD}