spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE.HOST}:${DATABASE.PORT}/${DATABASE.NAME}?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=UTC&useSSL=false
    username: ${DATABASE.USERNAME}
    password: ${DATABASE.PASSWORD}
